CREATE TABLE MESSAGE (
  ID NUMBER               NOT NULL 
, CONVERSATION_IDENTIFIER VARCHAR2(40 CHAR)   
, MESSAGE_TYPE            VARCHAR2(100)
, MESSAGE_DATE            DATE NOT NULL  
, STATE                   VARCHAR2(20) DEFAULT 'OK'
, SENDER                  VARCHAR2(200 CHAR)
, RECEIVER                VARCHAR2(200 CHAR)    
, CONSTRAINT MESSAGE_PK PRIMARY KEY  ( ID )
);

CREATE INDEX MESSAGE_CONVERSATION_IDX ON MESSAGE (CONVERSATION_IDENTIFIER) ;

CREATE SEQUENCE MESSAGE_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 0 CACHE 20;

