package osb.book.soap.jms;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Sat Jun 11 22:38:09 CEST 2011  
 */

public interface HelloWorldService extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://wsrm.osbbook}sayHello   */

  public java.lang.String sayHello() throws java.rmi.RemoteException;
    public void sayHelloAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
  
}